"""
PDF Report Generator Module
Version: 2.1.0
Author: Taiwo Durodola-Tunde

Generates professional PDF reports for GRC governance reporting.
Includes both a legacy single-page summary and an enhanced
multi-page management report.

Functions:
    generate_pdf: Single-page executive summary (legacy).
    generate_enhanced_pdf: Multi-page management report.
"""

from datetime import datetime
from io import BytesIO

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch, cm
from reportlab.pdfgen import canvas
from reportlab.platypus import (
    SimpleDocTemplate,
    Table,
    TableStyle,
    Paragraph,
    Spacer,
    PageBreak,
)


# ==========================================================
# CONFIGURATION
# ==========================================================

# Passed from main app — avoids circular import
_APP_VERSION = "2.2.0-alpha.1"


def set_version(version: str):
    """Set the app version used in PDF footers."""
    global _APP_VERSION
    _APP_VERSION = version


# ==========================================================
# LEGACY PDF GENERATOR
# ==========================================================

def generate_pdf(
    compliance_score,
    metrics,
    rating
):
    """
    Legacy PDF generator — single-page executive summary.

    Retained for backward compatibility with existing workflows
    and quick one-page exports.

    Args:
        compliance_score (float): Current compliance percentage.
        metrics (dict): Dictionary with open_risks, closed_risks, high_risks.
        rating (str): Health rating string with emoji indicator.

    Returns:
        BytesIO: Buffer containing the generated PDF document.
    """

    buffer = BytesIO()

    pdf = canvas.Canvas(buffer, pagesize=letter)
    pdf.setTitle("Executive GRC Report")

    # Title
    pdf.setFont("Helvetica-Bold", 16)
    pdf.drawString(50, 750, "Executive GRC Report")

    # Body
    pdf.setFont("Helvetica", 12)
    pdf.drawString(
        50, 720,
        f"Generated: {datetime.now().strftime('%d %B %Y %H:%M')}"
    )
    pdf.drawString(
        50, 690,
        f"Compliance Score: {compliance_score}%"
    )
    pdf.drawString(50, 670, f"Status: {rating}")
    pdf.drawString(
        50, 650,
        f"Open Risks: {metrics['open_risks']}"
    )
    pdf.drawString(
        50, 630,
        f"Closed Risks: {metrics['closed_risks']}"
    )
    pdf.drawString(
        50, 610,
        f"High Risks: {metrics['high_risks']}"
    )
    pdf.drawString(
        50, 580,
        f"Dashboard Version: {_APP_VERSION}"
    )
    pdf.drawString(
        50, 560,
        "Generated by GRC Compliance Dashboard"
    )

    pdf.save()
    buffer.seek(0)

    return buffer


# ==========================================================
# ENHANCED MULTI-PAGE PDF GENERATOR
# ==========================================================

def generate_enhanced_pdf(
    compliance_score,
    metrics,
    rating,
    risk_df,
    controls_df,
    escalated_df,
    trend_df=None
):
    """
    Enhanced multi-page PDF report for monthly management reporting.

    Generates a comprehensive 5-page PDF:
        - Page 1: Executive Summary with KPIs and health rating
        - Page 2: Risk Register breakdown by level and owner
        - Page 3: Escalation Status with overdue risk details
        - Page 4: Control Coverage and compliance trend
        - Page 5: Recommendations and sign-off section

    Args:
        compliance_score (float): Current compliance percentage.
        metrics (dict): Risk count metrics.
        rating (str): Health rating string.
        risk_df (DataFrame): Full risk register data.
        controls_df (DataFrame): Control implementation data.
        escalated_df (DataFrame): Risk data with escalation applied.
        trend_df (DataFrame, optional): Compliance history data.

    Returns:
        BytesIO: Buffer containing the multi-page PDF document.
    """

    buffer = BytesIO()

    # Document setup
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=1.5 * cm,
        leftMargin=1.5 * cm,
        topMargin=2 * cm,
        bottomMargin=2 * cm
    )

    # Stylesheet configuration
    styles = getSampleStyleSheet()

    styles.add(ParagraphStyle(
        name="ReportTitle",
        parent=styles["Title"],
        fontSize=22,
        spaceAfter=20,
        textColor=colors.HexColor("#1a237e")
    ))

    styles.add(ParagraphStyle(
        name="SectionHeader",
        parent=styles["Heading2"],
        fontSize=14,
        spaceAfter=12,
        spaceBefore=16,
        textColor=colors.HexColor("#283593")
    ))

    styles.add(ParagraphStyle(
        name="ReportBody",
        parent=styles["Normal"],
        fontSize=10,
        spaceAfter=8,
        leading=14
    ))

    styles.add(ParagraphStyle(
        name="ReportFooter",
        parent=styles["Normal"],
        fontSize=8,
        textColor=colors.grey
    ))

    elements = []

    # ==== PAGE 1: EXECUTIVE SUMMARY ====
    elements.append(
        Paragraph("Monthly GRC Management Report", styles["ReportTitle"])
    )
    elements.append(
        Paragraph(
            f"Report Period: {datetime.now().strftime('%B %Y')}",
            styles["ReportBody"]
        )
    )
    elements.append(
        Paragraph(
            f"Generated: {datetime.now().strftime('%d %B %Y %H:%M')}",
            styles["ReportBody"]
        )
    )
    elements.append(
        Paragraph(
            f"Dashboard Version: {_APP_VERSION}",
            styles["ReportBody"]
        )
    )
    elements.append(Spacer(1, 0.5 * inch))

    elements.append(
        Paragraph("1. Executive Summary", styles["SectionHeader"])
    )

    # Clean rating text (remove emoji for PDF)
    rating_text = (
        rating.replace("🟢 ", "")
        .replace("🟠 ", "")
        .replace("🔴 ", "")
    )

    elements.append(
        Paragraph(
            f"The current compliance posture is rated as "
            f"<b>{rating_text}</b> with an overall score of "
            f"<b>{compliance_score}%</b>.",
            styles["ReportBody"]
        )
    )
    elements.append(Spacer(1, 0.3 * inch))

    # KPI Summary Table
    kpi_data = [
        ["Metric", "Value", "Status"],
        ["Compliance Score", f"{compliance_score}%", rating_text],
        [
            "Total Open Risks",
            str(metrics["open_risks"]),
            "Action Required" if metrics["open_risks"] > 0 else "Clear"
        ],
        [
            "High Priority Risks",
            str(metrics["high_risks"]),
            "Critical" if metrics["high_risks"] > 3 else "Manageable"
        ],
        ["Closed Risks", str(metrics["closed_risks"]), "Resolved"],
        ["Total Risks Tracked", str(len(risk_df)), "Active Monitoring"],
    ]

    kpi_table = Table(
        kpi_data,
        colWidths=[2.5 * inch, 1.5 * inch, 2.0 * inch]
    )
    kpi_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1a237e")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 10),
        ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
        ("FONTSIZE", (0, 1), (-1, -1), 9),
        ("ALIGN", (1, 0), (1, -1), "CENTER"),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("BACKGROUND", (0, 1), (-1, 1), colors.HexColor("#e8eaf6")),
        ("BACKGROUND", (0, 3), (-1, 3), colors.HexColor("#e8eaf6")),
        ("BACKGROUND", (0, 5), (-1, 5), colors.HexColor("#e8eaf6")),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))
    elements.append(kpi_table)

    # ==== PAGE 2: RISK REGISTER BREAKDOWN ====
    elements.append(PageBreak())
    elements.append(
        Paragraph("2. Risk Register Analysis", styles["SectionHeader"])
    )
    elements.append(
        Paragraph(
            "The following table summarises the current risk register "
            "by owner and severity level.",
            styles["ReportBody"]
        )
    )
    elements.append(Spacer(1, 0.3 * inch))

    # Risk by Owner Table
    owner_agg = (
        risk_df.groupby("Risk_Owner")
        .agg(
            Total=("Risk_ID", "count"),
            High=("Risk_Level", lambda x: (x == "High").sum()),
            Medium=("Risk_Level", lambda x: (x == "Medium").sum()),
            Low=("Risk_Level", lambda x: (x == "Low").sum()),
            Open=("Status", lambda x: (x == "Open").sum()),
            Closed=("Status", lambda x: (x == "Closed").sum()),
        )
        .reset_index()
    )

    risk_table_data = [
        ["Risk Owner", "Total", "High", "Medium", "Low", "Open", "Closed"]
    ]
    for _, row in owner_agg.iterrows():
        risk_table_data.append([
            str(row["Risk_Owner"]),
            str(row["Total"]),
            str(row["High"]),
            str(row["Medium"]),
            str(row["Low"]),
            str(row["Open"]),
            str(row["Closed"]),
        ])

    risk_table = Table(
        risk_table_data,
        colWidths=[
            2.0 * inch, 0.7 * inch, 0.7 * inch,
            0.9 * inch, 0.7 * inch, 0.7 * inch, 0.8 * inch
        ]
    )
    risk_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#c62828")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 9),
        ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
        ("FONTSIZE", (0, 1), (-1, -1), 8),
        ("ALIGN", (1, 0), (-1, -1), "CENTER"),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ]))
    elements.append(risk_table)
    elements.append(Spacer(1, 0.4 * inch))

    # Risk Level Summary
    elements.append(
        Paragraph("2.1 Risk Level Distribution", styles["SectionHeader"])
    )
    level_summary = risk_df["Risk_Level"].value_counts()
    for level in ["High", "Medium", "Low"]:
        count = level_summary.get(level, 0)
        elements.append(
            Paragraph(
                f"<b>{level}:</b> {count} risks "
                f"({round(count / len(risk_df) * 100, 1)}% of total)",
                styles["ReportBody"]
            )
        )

    # ==== PAGE 3: ESCALATION STATUS ====
    elements.append(PageBreak())
    elements.append(
        Paragraph("3. Escalation Status Report", styles["SectionHeader"])
    )

    overdue_risks = escalated_df[escalated_df["Is_Overdue"] == True]
    total_overdue = len(overdue_risks)

    elements.append(
        Paragraph(
            f"There are currently <b>{total_overdue}</b> overdue risks "
            f"requiring escalation action.",
            styles["ReportBody"]
        )
    )
    elements.append(Spacer(1, 0.2 * inch))

    if total_overdue > 0:
        esc_table_data = [
            ["Risk ID", "Risk Name", "Owner", "Days Overdue", "Escalation"]
        ]
        for _, row in overdue_risks.sort_values(
            "Days_Overdue", ascending=False
        ).iterrows():
            esc_table_data.append([
                str(row["Risk_ID"]),
                str(row["Risk_Name"])[:30],
                str(row["Risk_Owner"])[:20],
                str(int(row["Days_Overdue"])),
                str(row["Escalation_Level"]).replace("Level ", "L")[:25],
            ])

        esc_table = Table(
            esc_table_data,
            colWidths=[
                0.8 * inch, 2.0 * inch, 1.5 * inch,
                1.0 * inch, 1.8 * inch
            ]
        )
        esc_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#e65100")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, 0), 9),
            ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
            ("FONTSIZE", (0, 1), (-1, -1), 8),
            ("ALIGN", (3, 0), (3, -1), "CENTER"),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ]))
        elements.append(esc_table)
    else:
        elements.append(
            Paragraph(
                "No overdue risks at this time. All open risks "
                "are within their remediation deadlines.",
                styles["ReportBody"]
            )
        )

    # ==== PAGE 4: CONTROL COVERAGE & TREND ====
    elements.append(PageBreak())
    elements.append(
        Paragraph(
            "4. Control Coverage & Compliance Trend",
            styles["SectionHeader"]
        )
    )
    elements.append(
        Paragraph(
            "4.1 ISO 27001 Control Implementation Status",
            styles["SectionHeader"]
        )
    )

    control_counts = controls_df["Status"].value_counts()
    total_controls = len(controls_df)

    ctrl_table_data = [["Control Status", "Count", "Percentage"]]
    for status in ["Implemented", "In Progress", "Planned"]:
        count = control_counts.get(status, 0)
        pct = round(count / total_controls * 100, 1) if total_controls > 0 else 0
        ctrl_table_data.append([status, str(count), f"{pct}%"])

    ctrl_table = Table(
        ctrl_table_data,
        colWidths=[2.0 * inch, 1.5 * inch, 1.5 * inch]
    )
    ctrl_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#2e7d32")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 10),
        ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
        ("FONTSIZE", (0, 1), (-1, -1), 9),
        ("ALIGN", (1, 0), (-1, -1), "CENTER"),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))
    elements.append(ctrl_table)
    elements.append(Spacer(1, 0.4 * inch))

    # Compliance Trend
    elements.append(
        Paragraph("4.2 Compliance Score Trend", styles["SectionHeader"])
    )

    if trend_df is not None and not trend_df.empty:
        trend_table_data = [["Month", "Score (%)", "Movement"]]
        prev_score = None
        for _, row in trend_df.iterrows():
            score = row["Score"]
            if prev_score is not None:
                movement = score - prev_score
                movement_str = f"+{movement}" if movement > 0 else str(movement)
            else:
                movement_str = "-"
            trend_table_data.append([
                str(row["Month"]), str(score), movement_str
            ])
            prev_score = score

        trend_table = Table(
            trend_table_data,
            colWidths=[1.5 * inch, 1.5 * inch, 1.5 * inch]
        )
        trend_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1565c0")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, 0), 10),
            ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
            ("FONTSIZE", (0, 1), (-1, -1), 9),
            ("ALIGN", (1, 0), (-1, -1), "CENTER"),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
            ("TOPPADDING", (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ]))
        elements.append(trend_table)
    else:
        elements.append(
            Paragraph(
                "Compliance trend data not available for this period.",
                styles["ReportBody"]
            )
        )

    # ==== PAGE 5: RECOMMENDATIONS & SIGN-OFF ====
    elements.append(PageBreak())
    elements.append(
        Paragraph("5. Recommendations & Next Steps", styles["SectionHeader"])
    )

    recommendations = []

    if metrics["high_risks"] > 0:
        recommendations.append(
            f"Prioritise remediation of {metrics['high_risks']} "
            f"high-severity risks currently in the register."
        )
    if total_overdue > 0:
        recommendations.append(
            f"Escalate {total_overdue} overdue risk(s) to the "
            f"appropriate governance forum for immediate action."
        )
    if compliance_score < 80:
        recommendations.append(
            "Target 80% compliance threshold by accelerating "
            "control implementation for In Progress and Planned items."
        )
    planned_controls = control_counts.get("Planned", 0)
    if planned_controls > 0:
        recommendations.append(
            f"Initiate implementation planning for {planned_controls} "
            f"controls currently in 'Planned' status."
        )
    if not recommendations:
        recommendations.append(
            "Maintain current compliance posture and continue "
            "monitoring risk register for emerging threats."
        )

    for i, rec in enumerate(recommendations, 1):
        elements.append(
            Paragraph(f"{i}. {rec}", styles["ReportBody"])
        )

    elements.append(Spacer(1, 0.5 * inch))

    # Sign-off section
    elements.append(
        Paragraph("6. Report Sign-Off", styles["SectionHeader"])
    )

    signoff_data = [
        ["Role", "Name", "Date", "Signature"],
        ["Report Author", "", datetime.now().strftime("%d/%m/%Y"), ""],
        ["Reviewed By", "", "", ""],
        ["Approved By", "", "", ""],
    ]
    signoff_table = Table(
        signoff_data,
        colWidths=[1.5 * inch, 2.0 * inch, 1.2 * inch, 1.8 * inch]
    )
    signoff_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#37474f")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 9),
        ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
        ("FONTSIZE", (0, 1), (-1, -1), 9),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("TOPPADDING", (0, 0), (-1, -1), 10),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
    ]))
    elements.append(signoff_table)
    elements.append(Spacer(1, 0.5 * inch))

    # Footer
    elements.append(
        Paragraph(
            "CONFIDENTIAL - For internal governance use only.",
            styles["ReportFooter"]
        )
    )
    elements.append(
        Paragraph(
            f"Generated by GRC Compliance Dashboard v{_APP_VERSION}",
            styles["ReportFooter"]
        )
    )

    # Build document
    doc.build(elements)
    buffer.seek(0)

    return buffer
